### ISSUE TITLE
"Couldn't load phase1radix2m" when running MPCParameters::new()

### ISSUE THREAD

**Issue by mschoenebeck** [ebfull/phase2#5]
I am trying to use the library for a mpc for a custom circuit. Unfortunately when I call `MPCParameters::new()` with any circuit it panics because there is a file missing which it tries to load from the file system: "phase1radix2m". I assume it contains some initial parameters or configuration. Could you upload a sample file or give some information about how to create it? That would be great.

Thank you so much for open sourcing all that code. It really helped me a lot!

**Comment by str4d** [comment]
You can download the phase 1 files from here: https://download.z.cash/downloads/powersoftau/

Each sequential file enables a larger circuit. You'll need all of the files starting from `phase1radix2m0` up to `phase1radix2mX` where `2^X` is the maximum size of your circuit.

**Comment by mschoenebeck** [comment]
Great! Thanks a lot!

**Comment by passer-byzhang** [comment]
May I ask a question, these files seems like a file of Point list and the program read them 
 in sequence when creating a pvk as parameters .
Is it that I just need to modify the `rng` of `params.contribute(rng);` If I want to use my own parameters to generate pvk?
